name: Terraform CI Pipeline

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive -check

      - name: Terraform validate
        run: terraform validate